// agentpanel — GOAGENT-style AGENT TEAM sidebar for the pi TUI.
//
// A true right-side sidebar: nonCapturing pi-tui overlay anchored top-right —
// chat keeps the left side and keyboard focus (same mechanism as sa-browser).
// Visibility comes from a SOLID background fill + accent left edge: without
// them the panel is floating text and the chat bleeds straight through it.
//
// Sections: header (working count) → shared board task → working agents
// (dot+spinner, ⚙ tool ticker, last words) → idle agents (one dim line each)
// → RUNNING workflows (from `workflow runs` — visible even when the gateway
// is down) → /team hint.
//
// Data: `gateway agents` TSV — name, state, own-task, role, busy-secs, tokens, tools, words
// (see crates/gateway/src/server.rs write_agents — keep in sync!) and
// `workflow runs` TSV. Display only — no logic.
// Auto-activates in the TUI; `/team` toggles.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFile } from "node:child_process";
import { join } from "node:path";
import { BIN, ROOT, layout, vwidth } from "./lib/statusline-common.ts";
const REFRESH_MS = 10000;
const PANE_WIDTH = 58; // wide: pixel avatars + full card content

const RESET = "\x1b[0m";
const BG = "\x1b[48;5;235m"; // solid panel background — the visibility fix
const BODY = "\x1b[38;5;250m"; // explicit body fg — every fragment restores it
const EDGE = `\x1b[38;5;60m▌${BODY}`;
// Self-contained color fragments: each sets its fg and restores BODY after —
// nothing inherits the edge color, and no SGR dim (dim over a dark bg is
// muddy and theme-dependent; explicit grays are predictable).
const fg = (c: string, s: string) => `\x1b[38;5;${c}m${s}${BODY}`;
const dim = (s: string) => fg("244", s);
const bold = (s: string) => `\x1b[1m${s}\x1b[22m`;
const ACCENTS = ["212", "80", "150", "215", "141", "117"];

// Pixel-art avatars: 16x15px per character rendered to sextant cells (2x3
// px/cell, same encoding as sa-browser) — 8 cols x 5 rows, truecolor. Art is
// GENERATED by .scratch/gen-faces.ts and embedded as display data.
// Idle cards keep a one-line kaomoji; working cards get the full face.
const FACE_ART: Record<string, string[]> = {
	linus: [
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;205;165;110m\x1b[48;2;38;38;38m🬦\x1b[38;2;205;165;110m\x1b[48;2;38;38;38m🬹\x1b[38;2;205;165;110m\x1b[48;2;38;38;38m🬹\x1b[38;2;205;165;110m\x1b[48;2;38;38;38m🬹\x1b[38;2;205;165;110m\x1b[48;2;38;38;38m🬹\x1b[38;2;205;165;110m\x1b[48;2;38;38;38m🬓\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;205;165;110m\x1b[48;2;252;205;165m🬆\x1b[38;2;252;205;165m\x1b[48;2;205;165;110m🬹\x1b[38;2;252;205;165m\x1b[48;2;205;165;110m🬹\x1b[38;2;252;205;165m\x1b[48;2;205;165;110m🬹\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬱\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;255;255;255m🬕\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;255;255;255m🬕\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬥\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬎\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬙\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
	],
	ada: [
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;70;45;30m\x1b[48;2;38;38;38m🬦\x1b[38;2;70;45;30m\x1b[48;2;38;38;38m🬹\x1b[38;2;70;45;30m\x1b[48;2;38;38;38m🬹\x1b[38;2;70;45;30m\x1b[48;2;38;38;38m🬹\x1b[38;2;255;120;180m\x1b[48;2;70;45;30m▐\x1b[38;2;255;120;180m\x1b[48;2;38;38;38m🬳\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;70;45;30m\x1b[48;2;252;205;165m🬕\x1b[38;2;252;205;165m\x1b[48;2;70;45;30m🬹\x1b[38;2;252;205;165m\x1b[48;2;70;45;30m🬹\x1b[38;2;252;205;165m\x1b[48;2;70;45;30m🬹\x1b[38;2;252;205;165m\x1b[48;2;70;45;30m🬹\x1b[38;2;70;45;30m\x1b[48;2;252;205;165m🬨\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;70;45;30m🬷\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬕\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬕\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;70;45;30m🬲\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬥\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬴\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬎\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬎\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬸\x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬙\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
	],
	grace: [
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;40;40;45m\x1b[48;2;38;38;38m🬦\x1b[38;2;40;40;45m\x1b[48;2;38;38;38m🬹\x1b[38;2;40;40;45m\x1b[48;2;38;38;38m🬻\x1b[38;2;40;40;45m\x1b[48;2;38;38;38m🬺\x1b[38;2;40;40;45m\x1b[48;2;38;38;38m🬹\x1b[38;2;40;40;45m\x1b[48;2;38;38;38m🬓\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬷\x1b[38;2;252;205;165m\x1b[48;2;40;40;45m🬹\x1b[38;2;252;205;165m\x1b[48;2;40;40;45m🬹\x1b[38;2;252;205;165m\x1b[48;2;40;40;45m🬹\x1b[38;2;252;205;165m\x1b[48;2;40;40;45m🬹\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬲\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;20;20;20m\x1b[48;2;255;255;255m🬕\x1b[38;2;20;20;20m\x1b[48;2;35;35;50m🬨\x1b[38;2;20;20;20m\x1b[48;2;255;255;255m🬕\x1b[38;2;20;20;20m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬥\x1b[38;2;252;205;165m\x1b[48;2;20;20;20m🬹\x1b[38;2;20;20;20m\x1b[48;2;252;205;165m🬰\x1b[38;2;20;20;20m\x1b[48;2;252;205;165m🬰\x1b[38;2;252;205;165m\x1b[48;2;20;20;20m🬹\x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬙\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
	],
	ken: [
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;150;150;155m\x1b[48;2;38;38;38m🬦\x1b[38;2;150;150;155m\x1b[48;2;38;38;38m🬹\x1b[38;2;150;150;155m\x1b[48;2;38;38;38m🬹\x1b[38;2;150;150;155m\x1b[48;2;38;38;38m🬹\x1b[38;2;150;150;155m\x1b[48;2;38;38;38m🬹\x1b[38;2;150;150;155m\x1b[48;2;38;38;38m🬓\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬷\x1b[38;2;252;205;165m\x1b[48;2;150;150;155m🬹\x1b[38;2;252;205;165m\x1b[48;2;150;150;155m🬹\x1b[38;2;252;205;165m\x1b[48;2;150;150;155m🬹\x1b[38;2;252;205;165m\x1b[48;2;150;150;155m🬹\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬲\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;255;255;255m🬕\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;255;255;255m🬕\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬥\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬎\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬙\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
	],
	dennis: [
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;60;50;45m\x1b[48;2;38;38;38m🬦\x1b[38;2;60;50;45m\x1b[48;2;38;38;38m🬹\x1b[38;2;60;50;45m\x1b[48;2;38;38;38m🬹\x1b[38;2;60;50;45m\x1b[48;2;38;38;38m🬹\x1b[38;2;60;50;45m\x1b[48;2;38;38;38m🬹\x1b[38;2;60;50;45m\x1b[48;2;38;38;38m🬓\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬷\x1b[38;2;252;205;165m\x1b[48;2;60;50;45m🬹\x1b[38;2;252;205;165m\x1b[48;2;60;50;45m🬹\x1b[38;2;252;205;165m\x1b[48;2;60;50;45m🬹\x1b[38;2;252;205;165m\x1b[48;2;60;50;45m🬹\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬲\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;255;255;255m🬕\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;255;255;255m🬕\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬥\x1b[38;2;252;205;165m\x1b[48;2;60;50;45m🬴\x1b[38;2;252;205;165m\x1b[48;2;60;50;45m🬰\x1b[38;2;252;205;165m\x1b[48;2;60;50;45m🬰\x1b[38;2;252;205;165m\x1b[48;2;60;50;45m🬸\x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬙\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
	],
	margaret: [
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;120;80;50m\x1b[48;2;38;38;38m🬦\x1b[38;2;120;80;50m\x1b[48;2;38;38;38m🬹\x1b[38;2;120;80;50m\x1b[48;2;38;38;38m🬻\x1b[38;2;120;80;50m\x1b[48;2;38;38;38m🬺\x1b[38;2;120;80;50m\x1b[48;2;38;38;38m🬹\x1b[38;2;120;80;50m\x1b[48;2;38;38;38m🬓\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬷\x1b[38;2;252;205;165m\x1b[48;2;120;80;50m🬹\x1b[38;2;252;205;165m\x1b[48;2;120;80;50m🬹\x1b[38;2;252;205;165m\x1b[48;2;120;80;50m🬹\x1b[38;2;252;205;165m\x1b[48;2;120;80;50m🬹\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬲\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;90;60;40m\x1b[48;2;255;255;255m🬕\x1b[38;2;90;60;40m\x1b[48;2;35;35;50m🬨\x1b[38;2;90;60;40m\x1b[48;2;255;255;255m🬕\x1b[38;2;90;60;40m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬥\x1b[38;2;252;205;165m\x1b[48;2;90;60;40m🬹\x1b[38;2;90;60;40m\x1b[48;2;252;205;165m🬰\x1b[38;2;90;60;40m\x1b[48;2;252;205;165m🬰\x1b[38;2;252;205;165m\x1b[48;2;90;60;40m🬹\x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬙\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
	],
	turing: [
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;50;45;40m\x1b[48;2;38;38;38m🬦\x1b[38;2;50;45;40m\x1b[48;2;38;38;38m🬹\x1b[38;2;50;45;40m\x1b[48;2;38;38;38m🬹\x1b[38;2;50;45;40m\x1b[48;2;38;38;38m🬹\x1b[38;2;50;45;40m\x1b[48;2;38;38;38m🬹\x1b[38;2;50;45;40m\x1b[48;2;38;38;38m🬓\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;50;45;40m\x1b[48;2;252;205;165m🬆\x1b[38;2;252;205;165m\x1b[48;2;50;45;40m🬹\x1b[38;2;252;205;165m\x1b[48;2;50;45;40m🬹\x1b[38;2;252;205;165m\x1b[48;2;50;45;40m🬹\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬱\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬕\x1b[38;2;252;205;165m\x1b[48;2;255;255;255m🬨\x1b[38;2;252;205;165m\x1b[48;2;35;35;50m🬕\x1b[38;2;252;205;165m\x1b[48;2;255;255;255m🬨\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬥\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬎\x1b[38;2;252;205;165m\x1b[48;2;195;95;85m🬎\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬙\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;252;205;165m\x1b[48;2;120;170;255m🬆\x1b[38;2;252;205;165m\x1b[48;2;120;170;255m🬊\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬂\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
	],
	woz: [
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬦\x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬹\x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬹\x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬹\x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬹\x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬓\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬷\x1b[38;2;252;205;165m\x1b[48;2;110;75;50m🬹\x1b[38;2;252;205;165m\x1b[48;2;110;75;50m🬹\x1b[38;2;252;205;165m\x1b[48;2;110;75;50m🬹\x1b[38;2;252;205;165m\x1b[48;2;110;75;50m🬹\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m🬲\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;20;20;20m\x1b[48;2;35;35;50m🬕\x1b[38;2;20;20;20m\x1b[48;2;35;35;50m🬨\x1b[38;2;20;20;20m\x1b[48;2;35;35;50m🬕\x1b[38;2;20;20;20m\x1b[48;2;35;35;50m🬨\x1b[38;2;252;205;165m\x1b[48;2;38;38;38m█\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬥\x1b[38;2;20;20;20m\x1b[48;2;252;205;165m🬰\x1b[38;2;20;20;20m\x1b[48;2;252;205;165m🬰\x1b[38;2;20;20;20m\x1b[48;2;252;205;165m🬰\x1b[38;2;20;20;20m\x1b[48;2;252;205;165m🬰\x1b[38;2;252;205;165m\x1b[48;2;250;170;150m🬙\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
		"\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬎\x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬎\x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬎\x1b[38;2;110;75;50m\x1b[48;2;38;38;38m🬎\x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[38;2;38;38;38m\x1b[48;2;38;38;38m \x1b[49m",
	],
};

const FACE_W = 8;
const KAOMOJI: Record<string, string> = {
	linus: "(◕‿◕)", ada: "(◠‿◠)", grace: "(■‿■)", ken: "(•‿•)",
	dennis: "(◔‿◔)", margaret: "(☉‿☉)", turing: "(¬‿¬)", woz: "(^ω^)",
};
const faceArt = (name: string): string[] => FACE_ART[name] ?? FACE_ART.linus;
const kaomoji = (name: string): string => KAOMOJI[name] ?? "(◉‿◉)";

// Captured extension context — lets the panel read live session state
// (context-window usage) without owning any logic.
let ctxRef: any;

type Agent = { name: string; state: string; task: string; role: string; busySecs: number; tokens: string; tools: string; words: string };
type Run = { id: string; def: string; step: string; task: string };

let agents: Agent[] = [];
let runs: Run[] = [];
let gatewayUp = false;
// Module-scoped so the module-level refresh() callbacks can request a render.
// (Was function-local, which made refresh() throw "tuiRef is not defined" and
// crashed pi via an uncaughtException in the execFile exit handler.)
let tuiRef: any;
let frame = 0;
const SPIN = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];

function humanTokens(raw: string): string {
	const n = Number(raw);
	if (!Number.isFinite(n) || n <= 0) return "";
	if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + "m";
	if (n >= 1_000) return Math.round(n / 1_000) + "k";
	return String(n);
}

function refresh(): void {
	execFile(BIN("gateway"), ["agents"], { timeout: 3000, encoding: "utf8" }, (err, out) => {
		if (err) {
			agents = [];
			gatewayUp = false;
			tuiRef?.requestRender();
			return;
		}
		agents = out
			.split("\n")
			.filter((l) => l.includes("\t"))
			.map((l) => {
				const [name, state, task, role, busySecs, tokens, tools, words] = l.split("\t");
				return {
					name: name ?? "?",
					state: state ?? "idle",
					task: (task ?? "").trim(),
					role: role ?? "Agent",
					busySecs: Number(busySecs ?? 0) || 0,
					tokens: (tokens ?? "").trim(),
					tools: (tools ?? "").trim(),
					words: (words ?? "").trim(),
				};
			})
			// working first, then by name — the active agents get the eye
			.sort((a, b) => Number(b.state === "working") - Number(a.state === "working") || a.name.localeCompare(b.name));
		gatewayUp = true;
		tuiRef?.requestRender();
	});
	execFile(BIN("workflow"), ["runs", "--live", "--db", join(ROOT, "data", "workflow.semdb"), "--tasks-db", join(ROOT, "data", "tasks.semdb")], { timeout: 3000, encoding: "utf8" }, (err, out) => {
		if (err) {
			runs = [];
			tuiRef?.requestRender();
			return;
		}
		runs = out
			.split("\n")
			.filter((l) => l.includes("\t") && !/\t(done|aborted)\t/.test(l))
			.map((l) => {
				const [id, def, _state, step, task] = l.split("\t");
				return { id: id ?? "?", def: def ?? "", step: (step ?? "").replace("step ", ""), task: (task ?? "").trim() };
			})
			.slice(0, 4);
		tuiRef?.requestRender();
	});
}

const vlen = (s: string) => vwidth(s); // cell-accurate (kitty wcwidth)
const clip = (s: string, w: number) => (s.length > w ? s.slice(0, Math.max(0, w - 1)) + "…" : s);
function marquee(s: string, width: number, tick: number): string {
	const clean = s.trim();
	if (width <= 0) return "";
	if (!clean) return "";
	if (vlen(clean) <= width) return clean + " ".repeat(Math.max(0, width - vlen(clean)));
	const loop = `${clean}   •   `;
	let out = "";
	let i = tick % loop.length;
	while (vlen(out) < width + 1) {
		out += loop[i % loop.length];
		i++;
	}
	return clip(out, width);
}

const humanBusy = (secs: number) => {
	if (!secs) return "";
	if (secs < 60) return `${secs}s`;
	const mins = Math.floor(secs / 60);
	if (mins < 60) return `${mins}m`;
	return `${Math.floor(mins / 60)}h${mins % 60}m`;
};

/** One padded panel row: accent edge + content on the solid background. */
function row(content: string, width: number): string {
	const inner = width - 2; // edge + one space of padding
	const pad = Math.max(0, inner - vlen(content));
	return `${BG}${EDGE} ${content}${" ".repeat(pad)}${RESET}`;
}

function rule(width: number): string {
	return row(dim("─".repeat(Math.max(4, width - 4))), width);
}

/** Framed card with rounded corners — one per agent, for visual separation. */
function card(content: string[], borderCol: string, width: number): string[] {
	const cw = Math.max(10, width - 4); // fits inside row()'s content area
	const b = (s: string) => fg(borderCol, s);
	const out: string[] = [row(b("╭" + "─".repeat(cw - 2) + "╮"), width)];
	for (const c of content) {
		const pad = Math.max(0, cw - 4 - vlen(c));
		out.push(row(b("│") + " " + c + " ".repeat(pad) + " " + b("│"), width));
	}
	out.push(row(b("╰" + "─".repeat(cw - 2) + "╯"), width));
	return out;
}

function render(width: number): string[] {
	const w = Math.max(24, width);
	const inner = w - 4;
	const lines: string[] = [];
	const working = agents.filter((a) => a.state === "working");

	// Header: name + live status count — green when active, orange when the
	// whole fleet idles (status colors, never gray: the panel must look alive).
	const count = working.length ? `${working.length}/${agents.length} working` : "all idle";
	const gap = " ".repeat(Math.max(1, inner - vlen("AGENT TEAM") - count.length));
	lines.push(row(bold(fg("255", "AGENT TEAM")) + gap + (working.length ? fg("46", count) : fg("208", count)), w));
	lines.push(rule(w));
	// Context-window usage bar: fills as this session's context is consumed.
	{
		const u = ctxRef?.getContextUsage?.();
		if (u && u.percent != null) {
			const pct = Math.min(100, Math.round(u.percent));
			const label = ` ${pct}%`;
			const kk = `${Math.round((u.tokens ?? 0) / 1000)}k/${Math.round(u.contextWindow / 1000)}k`;
			const barw = Math.max(8, inner - label.length - kk.length - 6);
			const fill = Math.round((pct / 100) * barw);
			const col = pct >= 80 ? "203" : pct >= 50 ? "215" : "78";
			const bar = fg(col, "▕" + "█".repeat(fill)) + fg("238", "░".repeat(Math.max(0, barw - fill))) + fg(col, "▏");
			lines.push(row(dim("ctx ") + bar + fg(col, label) + " " + dim(kk), w));
		} else {
			lines.push(row(dim("ctx ▕░░░░░░░░▏ —"), w));
		}
	}

	if (!gatewayUp) {
		lines.push(row(fg("203", "✖ gateway offline"), w));
		lines.push(row(dim("supervise status → up"), w));
	} else {
		lines.push(row("", w));

		// Stable accent per agent (by fleet position, not working-subset index)
		// so each agent keeps its color identity whether working or idle.
		const accentOf = (name: string) => ACCENTS[Math.max(0, agents.findIndex((x) => x.name === name)) % ACCENTS.length];

		const cardw = w - 8; // card content width for clipping
		working.forEach((a, i) => {
			const accent = accentOf(a.name);
			const spin = fg(accent, SPIN[(frame + i) % SPIN.length]);
			const textw = cardw - FACE_W - 1; // face column + gap
			const head = `${bold(fg(accent, a.name))} ${dim("· " + a.role)}`;
			const busyFor = humanBusy(a.busySecs);
			const state = fg("46", "● working ") + spin + (busyFor ? dim(" " + busyFor) : "");
			const gap1 = Math.max(1, textw - vlen(head) - vlen(state));
			const tok = humanTokens(a.tokens);
			const body: string[] = [head + " ".repeat(gap1) + state];
			const own = a.task && a.task !== "nothing" ? a.task : "";
			if (own) {
				// task sub-card: boxed row inside the agent card, padded to the
				// box width so short titles don't pull the border inward
				const boxw = Math.max(4, textw - 6);
				const inner = " ▣ " + clip(own, boxw - 5);
				body.push(fg("239", "┌" + "─".repeat(boxw) + "┐"));
				body.push(fg("239", "│") + fg("222", inner + " ".repeat(Math.max(0, boxw - vlen(inner)))) + fg("239", "│"));
				body.push(fg("239", "└" + "─".repeat(boxw) + "┘"));
			}
			if (a.tools) {
				const mw = Math.max(8, textw - 4);
				body.push(dim("⚙ ") + fg("253", marquee(a.tools, mw, frame)));
			}
			if (a.words) {
				// Two readable lines, bright — this is "what is it doing" for the
				// user; a dim clipped fragment defeated the panel's purpose.
				const max = (textw - 4) * 2;
				const wtext = clip(a.words, max);
				const l1 = wtext.slice(0, textw - 4);
				const l2 = wtext.slice(textw - 4);
				body.push(fg("250", "“" + l1 + (l2 ? "" : "”")));
				if (l2) body.push(fg("250", " " + l2 + "”"));
			}
			// Zip the 5-row pixel face beside the body rows (pad body to 5 so
			// the full face always shows). Each art row ends by resetting bg —
			// re-assert the panel bg + body fg before the text column.
			const face = faceArt(a.name);
			while (body.length < 5) body.push("");
			const zipped = body.map((rowText, ri) => {
				const f = ri < 5 ? face[ri] : " ".repeat(FACE_W);
				return f + BG + BODY + " " + rowText;
			});
			lines.push(...card(zipped, accent, w));
		});

		// Idle agents: one line each — orange status dot with a slow breathing
		// pulse, name in the agent's accent. Present but calm, never dead-gray.
		agents
			.filter((a) => a.state !== "working")
			.forEach((a, i) => {
				const tok = humanTokens(a.tokens);
				const pulse = (frame + i * 2) % 6 < 3 ? fg("208", "● idle") : fg("130", "● idle");
				const head = `${fg(accentOf(a.name), kaomoji(a.name))} ${fg("250", a.name)} ${dim("· " + a.role)}`;
				const right = pulse + " " + dim(tok);
				const gapw = Math.max(1, cardw - vlen(head) - vlen(right));
				lines.push(...card([head + " ".repeat(gapw) + right], "238", w));
			});
	}

	// RUNNING: in-flight workflows — answers "is anything running?" at a
	// glance. Pinned to the BOTTOM of the full-height pane; the gap between
	// the team block and it is filled with background rows so the sidebar
	// reads as one solid column for the whole terminal height.
	const bottom: string[] = [rule(w)];
	if (runs.length === 0) {
		bottom.push(row(dim("no workflows running"), w));
	} else {
		bottom.push(row(bold(fg("117", "RUNNING")) + " " + fg("117", SPIN[frame % SPIN.length]), w));
		runs.forEach((r, i) => {
			const arrow = (frame + i) % 4 < 2 ? fg("46", "▶") : fg("29", "▶");
			bottom.push(row(`${arrow} ${fg("117", r.id)} ${clip(r.def, 9)} ${dim("step")} ${fg("252", r.step)}${r.task ? dim(" → " + r.task) : ""}`, w));
		});
	}
	bottom.push(rule(w));
	bottom.push(row(dim("/team hide"), w));

	const termRows = process.stdout.rows ?? 40;
	const filler = Math.max(0, termRows - lines.length - bottom.length);
	for (let i = 0; i < filler; i++) lines.push(row("", w));
	lines.push(...bottom);
	return lines;
}

export default function (pi: ExtensionAPI) {
	let finish: ((r: unknown) => void) | undefined;
	let timer: ReturnType<typeof setInterval> | undefined;
	let spinTimer: ReturnType<typeof setInterval> | undefined;
	let active = false;

	function open(ctx: any): string {
		if (ctx.mode !== "tui") return "agent panel needs the interactive TUI";
		if (active) return "agent panel already active";
		active = true;
		layout.sidebarCols = PANE_WIDTH; // statusline lays out around the sidebar
		ctx.ui
			.custom(
				(tui: any, _theme: any, _kb: any, done: (r: unknown) => void) => {
					tuiRef = tui;
					finish = done;
					return {
						render(width: number): string[] {
							return render(width);
						},
						invalidate() {},
					};
				},
				{
					overlay: true,
					// nonCapturing is LOAD-BEARING: custom() otherwise gives the
					// overlay keyboard focus, and since this panel auto-opens at
					// session_start it would swallow ALL typing — dead editor.
					overlayOptions: () => ({ width: PANE_WIDTH, anchor: "top-right", maxHeight: "100%", nonCapturing: true }),
					onHandle: (h: any) => {
						if (h.isFocused?.()) h.unfocus?.();
					},
				},
			)
			.finally(() => {
				active = false;
				tuiRef = undefined;
			});
		refresh();
		if (!timer) timer = setInterval(() => {
			refresh();
		}, REFRESH_MS);
		// animation frames: cheap (cache-only render + pi-tui diffing), no
		// process spawns. Unconditional — the idle breathing pulse and the
		// RUNNING ticker keep the panel alive even when no agent is mid-turn.
		if (!spinTimer)
			spinTimer = setInterval(() => {
				frame++;
				tuiRef?.requestRender();
			}, 350);
		return "agent team sidebar on (right) — /team toggles";
	}

	function close(): string {
		if (timer) {
			clearInterval(timer);
			timer = undefined;
		}
		if (spinTimer) {
			clearInterval(spinTimer);
			spinTimer = undefined;
		}
		finish?.(undefined);
		finish = undefined;
		active = false;
		layout.sidebarCols = 0;
		return "agent team sidebar off";
	}

	pi.registerCommand("team", {
		description: "Toggle the AGENT TEAM sidebar (gateway fleet, GOAGENT-style)",
		handler: async (_args: string, ctx: any) => (active ? close() : open(ctx)),
	});

	pi.on("session_start", async (_e, ctx: any) => {
		ctxRef = ctx;
		if (ctx.mode === "tui" && !active) open(ctx);
	});
	pi.on("tool_execution_end", async (_e, ctx: any) => {
		ctxRef = ctx;
		tuiRef?.requestRender();
	});
	pi.on("turn_end", async (_e, ctx: any) => {
		ctxRef = ctx; // context usage updates after each turn's LLM response
		tuiRef?.requestRender();
	});
	pi.on("agent_end", async (_e, ctx: any) => {
		ctxRef = ctx;
		tuiRef?.requestRender();
	});
	pi.on("session_shutdown", async () => {
		close();
	});
}
