//! App shell: head/meta, logo header, tab rail, and tab routing. Owned by the
//! orchestrator — feature agents do NOT edit this file; they expose a component
//! and it gets wired here at merge time.

use dioxus::prelude::*;

const MAIN_CSS: Asset = asset!("/assets/main.css");
// Feature CSS that isn't self-linked by its component (sessions/blocks/commands).
const SESSIONS_CSS: Asset = asset!("/assets/sessions.css");
const BLOCKS_CSS: Asset = asset!("/assets/blocks.css");
const COMMANDS_CSS: Asset = asset!("/assets/commands.css");
pub const LOGO: Asset = asset!("/assets/logo.png");
pub const JEEVES: Asset = asset!("/assets/jeeves.png");

#[derive(Clone, Copy, PartialEq)]
pub enum Tab {
    Chat,
    Cowork,
    Code,
}

#[component]
pub fn App() -> Element {
    let tab = use_signal(|| Tab::Chat);
    rsx! {
        document::Stylesheet { href: MAIN_CSS }
        document::Stylesheet { href: SESSIONS_CSS }
        document::Stylesheet { href: BLOCKS_CSS }
        document::Stylesheet { href: COMMANDS_CSS }
        // Agent E: links theme.css (palette + safe-area tokens) and color-scheme.
        crate::theme::ThemeMeta {}
        document::Meta {
            name: "viewport",
            content: "width=device-width, initial-scale=1, viewport-fit=cover",
        }
        div { class: "app",
            Rail { tab }
            main { class: "pane",
                header { class: "topbar",
                    img { class: "logo-img", src: LOGO, alt: "SMARTAGENT" }
                }
                match tab() {
                    Tab::Chat => rsx! { crate::chat::Chat {} },
                    Tab::Cowork => rsx! { crate::cowork::Cowork {} },
                    Tab::Code => rsx! { crate::code::Code {} },
                }
            }
        }
    }
}

/// Pixel-art tab glyph — inline SVG, crisp-edged, themed via CSS `currentColor`.
fn tab_icon(tab: Tab) -> Element {
    let body = match tab {
        Tab::Chat => rsx! {
            rect { x: 1, y: 2, width: 14, height: 9, fill: "currentColor" }
            rect { x: 3, y: 11, width: 3, height: 3, fill: "currentColor" }
        },
        Tab::Cowork => rsx! {
            rect { x: 1, y: 2, width: 4, height: 12, fill: "currentColor" }
            rect { x: 6, y: 2, width: 4, height: 12, fill: "currentColor" }
            rect { x: 11, y: 2, width: 4, height: 12, fill: "currentColor" }
        },
        Tab::Code => rsx! {
            rect { x: 2, y: 6, width: 2, height: 2, fill: "currentColor" }
            rect { x: 4, y: 4, width: 2, height: 2, fill: "currentColor" }
            rect { x: 4, y: 8, width: 2, height: 2, fill: "currentColor" }
            rect { x: 12, y: 6, width: 2, height: 2, fill: "currentColor" }
            rect { x: 10, y: 4, width: 2, height: 2, fill: "currentColor" }
            rect { x: 10, y: 8, width: 2, height: 2, fill: "currentColor" }
        },
    };
    rsx! {
        svg {
            class: "tab-ico",
            width: "22",
            height: "22",
            view_box: "0 0 16 16",
            shape_rendering: "crispEdges",
            {body}
        }
    }
}

#[component]
fn Rail(tab: Signal<Tab>) -> Element {
    let item = |t: Tab, label: &'static str| {
        let active = tab() == t;
        rsx! {
            button {
                class: if active { "tab active" } else { "tab" },
                onclick: move |_| tab.set(t),
                {tab_icon(t)}
                span { class: "tab-label", "{label}" }
            }
        }
    };
    rsx! {
        aside { class: "rail",
            div { class: "logo", "◆" }
            nav {
                {item(Tab::Chat, "Chat")}
                {item(Tab::Cowork, "Cowork")}
                {item(Tab::Code, "Code")}
            }
            div { class: "rail-foot", "fleet" }
        }
    }
}
